'use client'

import { autoGenerateMenuAction, type RecipeSuggestion } from '@/app/actions/menu'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { cn } from '@/lib/utils'
import {
  AlertTriangle,
  CheckCircle2,
  Clock,
  Loader2,
  RefreshCw,
  Sparkles,
  Users,
} from 'lucide-react'
import Image from 'next/image'
import { useState } from 'react'
import { toast } from 'sonner'
import { AddMenuDialog } from './add-menu-dialog'
import type { MealTime } from '@/generated/prisma/client'
import type { Recipe } from '@/generated/prisma/client'

// ─── Props ────────────────────────────────────────────────────

interface AutoGenerateDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onDataChange: () => void
}

// ─── Component ────────────────────────────────────────────────

export function AutoGenerateDialog({ open, onOpenChange, onDataChange }: AutoGenerateDialogProps) {
  const [loading, setLoading] = useState(false)
  const [suggestions, setSuggestions] = useState<RecipeSuggestion[] | null>(null)

  // State cho dialog thêm món con
  const [addDialogOpen, setAddDialogOpen] = useState(false)
  const [selectedRecipe, setSelectedRecipe] = useState<Recipe | null>(null)
  const [selectedDate, setSelectedDate] = useState<string | null>(null)
  const [selectedMealTime, setSelectedMealTime] = useState<MealTime | null>(null)

  const handleGenerate = async () => {
    setLoading(true)
    setSuggestions(null)
    try {
      const result = await autoGenerateMenuAction(10)
      if (result.error) {
        toast.error(result.error)
      } else if (!result.suggestions || result.suggestions.length === 0) {
        toast.info('Không tìm thấy công thức nào phù hợp với nguyên liệu hiện có trong tủ.')
        setSuggestions([])
      } else {
        setSuggestions(result.suggestions)
      }
    } catch {
      toast.error('Lỗi khi tạo gợi ý.')
    } finally {
      setLoading(false)
    }
  }

  // Khi mở dialog lần đầu, tự động generate
  const handleOpenChange = (v: boolean) => {
    onOpenChange(v)
    if (v && suggestions === null) {
      handleGenerate()
    }
  }

  const handleAddToMenu = (suggestion: RecipeSuggestion) => {
    // Gợi ý ngày = hôm nay
    const today = new Date()
    today.setUTCHours(0, 0, 0, 0)
    setSelectedDate(today.toISOString())
    setSelectedMealTime('LUNCH')
    setSelectedRecipe(suggestion.recipe as unknown as Recipe)
    setAddDialogOpen(true)
  }

  return (
    <>
      <Dialog open={open} onOpenChange={handleOpenChange}>
        <DialogContent className='max-h-[85vh] overflow-y-auto sm:max-w-2xl'>
          <DialogHeader>
            <DialogTitle className='flex items-center gap-2 text-lg font-bold'>
              <Sparkles className='size-5 text-amber-500' />
              Gợi ý thực đơn từ tủ lạnh
            </DialogTitle>
            <DialogDescription>
              Công thức được gợi ý dựa trên nguyên liệu hiện có trong tủ lạnh. Ưu tiên nguyên liệu
              sắp hết hạn để tránh lãng phí.
            </DialogDescription>
          </DialogHeader>

          {/* Nút tạo lại */}
          <div className='flex justify-end'>
            <Button
              variant='outline'
              size='sm'
              onClick={handleGenerate}
              disabled={loading}
              className='gap-2'
            >
              {loading ? (
                <Loader2 className='size-3.5 animate-spin' />
              ) : (
                <RefreshCw className='size-3.5' />
              )}
              {loading ? 'Đang phân tích...' : 'Tạo lại gợi ý'}
            </Button>
          </div>

          {/* Nội dung */}
          {loading && (
            <div className='flex flex-col items-center justify-center gap-3 py-12 text-muted-foreground'>
              <Loader2 className='size-8 animate-spin text-amber-500' />
              <p className='text-sm'>Đang phân tích tủ lạnh và tìm công thức phù hợp...</p>
            </div>
          )}

          {!loading && suggestions !== null && suggestions.length === 0 && (
            <div className='rounded-xl border bg-muted/30 py-12 text-center'>
              <p className='font-medium text-muted-foreground'>
                Không có công thức nào phù hợp với nguyên liệu hiện tại.
              </p>
              <p className='mt-1 text-sm text-muted-foreground'>
                Hãy thêm nguyên liệu vào tủ lạnh hoặc thêm công thức mới.
              </p>
            </div>
          )}

          {!loading && suggestions && suggestions.length > 0 && (
            <div className='flex flex-col gap-3'>
              {suggestions.map((s) => (
                <div
                  key={s.recipe.id}
                  className={cn(
                    'flex items-start gap-3 rounded-xl border bg-card p-3 transition-shadow hover:shadow-md',
                    s.hasExpiringSoon &&
                      'border-amber-300/60 bg-amber-50/30 dark:border-amber-800/40 dark:bg-amber-950/20',
                  )}
                >
                  {/* Thumbnail */}
                  <div className='relative size-16 shrink-0 overflow-hidden rounded-lg border bg-muted'>
                    {s.recipe.thumbnail ? (
                      <Image
                        src={s.recipe.thumbnail}
                        alt={s.recipe.title}
                        fill
                        className='object-cover'
                      />
                    ) : (
                      <div className='flex h-full items-center justify-center text-2xl'>🍽️</div>
                    )}
                  </div>

                  {/* Info */}
                  <div className='flex min-w-0 flex-1 flex-col gap-1.5'>
                    <div className='flex flex-wrap items-start justify-between gap-1'>
                      <p className='leading-tight font-semibold'>{s.recipe.title}</p>
                      {s.hasExpiringSoon && (
                        <Badge
                          variant='outline'
                          className='shrink-0 border-amber-300 bg-amber-100 text-amber-700 dark:border-amber-700 dark:bg-amber-900/30 dark:text-amber-400'
                        >
                          <AlertTriangle className='mr-1 size-3' />
                          Dùng sắp hết hạn
                        </Badge>
                      )}
                    </div>

                    {/* Stats */}
                    <div className='flex flex-wrap items-center gap-3 text-xs text-muted-foreground'>
                      {/* Match score */}
                      <span className='flex items-center gap-1'>
                        <CheckCircle2 className='size-3.5 text-emerald-500' />
                        <span className='font-medium text-emerald-600 dark:text-emerald-400'>
                          {s.matchCount}/{s.totalIngredients} nguyên liệu
                        </span>
                      </span>

                      {/* Progress bar */}
                      <div className='flex items-center gap-1.5'>
                        <div className='h-1.5 w-20 overflow-hidden rounded-full bg-muted'>
                          <div
                            className={cn(
                              'h-full rounded-full transition-all',
                              s.matchScore === 1
                                ? 'bg-emerald-500'
                                : s.matchScore >= 0.7
                                  ? 'bg-teal-500'
                                  : s.matchScore >= 0.4
                                    ? 'bg-amber-500'
                                    : 'bg-muted-foreground/40',
                            )}
                            style={{ width: `${Math.round(s.matchScore * 100)}%` }}
                          />
                        </div>
                        <span>{Math.round(s.matchScore * 100)}%</span>
                      </div>

                      {/* Cook time */}
                      {(s.recipe.cookTime || s.recipe.prepTime) && (
                        <span className='flex items-center gap-1'>
                          <Clock className='size-3' />
                          {(s.recipe.prepTime || 0) + (s.recipe.cookTime || 0)} phút
                        </span>
                      )}

                      {/* Servings */}
                      {s.recipe.servings && (
                        <span className='flex items-center gap-1'>
                          <Users className='size-3' />
                          {s.recipe.servings} người
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Nút thêm */}
                  <Button
                    size='sm'
                    variant='outline'
                    className='shrink-0 border-teal-300 text-teal-600 hover:bg-teal-50 hover:text-teal-700 dark:border-teal-700 dark:text-teal-400'
                    onClick={() => handleAddToMenu(s)}
                  >
                    + Thêm
                  </Button>
                </div>
              ))}
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Dialog chọn ngày/bữa khi thêm từ gợi ý */}
      <AddMenuDialog
        open={addDialogOpen}
        onOpenChange={setAddDialogOpen}
        selectedDate={selectedDate}
        selectedMealTime={selectedMealTime}
        recipes={selectedRecipe ? [selectedRecipe] : []}
        defaultRecipeId={selectedRecipe?.id}
        onSuccess={() => {
          onDataChange()
          setAddDialogOpen(false)
        }}
      />
    </>
  )
}
